package br.com.bibliotech.view;

import br.com.bibliotech.controller.AluguelController;
import br.com.bibliotech.controller.LivroController;
import br.com.bibliotech.controller.ReservaController;
import br.com.bibliotech.controller.UsuarioController;
import javax.swing.JOptionPane;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnLivros = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnProfessores = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnAluguel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnAlunos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnReserva = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnFuncionarios = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtReservas = new javax.swing.JLabel();
        txtLivros = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAlugueis = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(38, 169, 108));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 246, 240));
        jLabel1.setText("BiblioTech");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 130));

        btnLivros.setBackground(new java.awt.Color(38, 169, 108));
        btnLivros.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLivrosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLivrosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLivrosMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cadastrar Livros");

        javax.swing.GroupLayout btnLivrosLayout = new javax.swing.GroupLayout(btnLivros);
        btnLivros.setLayout(btnLivrosLayout);
        btnLivrosLayout.setHorizontalGroup(
            btnLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLivrosLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(59, 59, 59))
        );
        btnLivrosLayout.setVerticalGroup(
            btnLivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnLivrosLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(43, 43, 43))
        );

        getContentPane().add(btnLivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 270, 120));

        btnProfessores.setBackground(new java.awt.Color(38, 169, 108));
        btnProfessores.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnProfessores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfessoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProfessoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProfessoresMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cadastrar Professores");

        javax.swing.GroupLayout btnProfessoresLayout = new javax.swing.GroupLayout(btnProfessores);
        btnProfessores.setLayout(btnProfessoresLayout);
        btnProfessoresLayout.setHorizontalGroup(
            btnProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProfessoresLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(36, 36, 36))
        );
        btnProfessoresLayout.setVerticalGroup(
            btnProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProfessoresLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(47, 47, 47))
        );

        getContentPane().add(btnProfessores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 270, 120));

        btnAluguel.setBackground(new java.awt.Color(38, 169, 108));
        btnAluguel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAluguel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAluguelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAluguelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAluguelMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alugar um livro");

        javax.swing.GroupLayout btnAluguelLayout = new javax.swing.GroupLayout(btnAluguel);
        btnAluguel.setLayout(btnAluguelLayout);
        btnAluguelLayout.setHorizontalGroup(
            btnAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAluguelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel7)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        btnAluguelLayout.setVerticalGroup(
            btnAluguelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAluguelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel7)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(btnAluguel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 270, -1));

        btnAlunos.setBackground(new java.awt.Color(38, 169, 108));
        btnAlunos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlunosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlunosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlunosMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastrar Alunos");

        javax.swing.GroupLayout btnAlunosLayout = new javax.swing.GroupLayout(btnAlunos);
        btnAlunos.setLayout(btnAlunosLayout);
        btnAlunosLayout.setHorizontalGroup(
            btnAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAlunosLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        btnAlunosLayout.setVerticalGroup(
            btnAlunosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAlunosLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(btnAlunos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 270, 120));

        btnReserva.setBackground(new java.awt.Color(38, 169, 108));
        btnReserva.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReservaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReservaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReservaMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Reservar um livro");

        javax.swing.GroupLayout btnReservaLayout = new javax.swing.GroupLayout(btnReserva);
        btnReserva.setLayout(btnReservaLayout);
        btnReservaLayout.setHorizontalGroup(
            btnReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReservaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel8)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        btnReservaLayout.setVerticalGroup(
            btnReservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReservaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel8)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        getContentPane().add(btnReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 270, -1));

        btnFuncionarios.setBackground(new java.awt.Color(38, 169, 108));
        btnFuncionarios.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFuncionariosMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cadastrar Funcionários");

        javax.swing.GroupLayout btnFuncionariosLayout = new javax.swing.GroupLayout(btnFuncionarios);
        btnFuncionarios.setLayout(btnFuncionariosLayout);
        btnFuncionariosLayout.setHorizontalGroup(
            btnFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFuncionariosLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(29, 29, 29))
        );
        btnFuncionariosLayout.setVerticalGroup(
            btnFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnFuncionariosLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(45, 45, 45))
        );

        getContentPane().add(btnFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 270, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Total de Aluguéis:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Total de livros:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        txtReservas.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtReservas.setForeground(new java.awt.Color(255, 255, 255));
        txtReservas.setText("0");
        getContentPane().add(txtReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        txtLivros.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtLivros.setForeground(new java.awt.Color(255, 255, 255));
        txtLivros.setText("0");
        getContentPane().add(txtLivros, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Total de reservas:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, -1, -1));

        txtAlugueis.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        txtAlugueis.setForeground(new java.awt.Color(255, 255, 255));
        txtAlugueis.setText("0");
        getContentPane().add(txtAlugueis, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 260, -1, -1));

        jPanel8.setBackground(new java.awt.Color(49, 81, 88));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 800, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLivrosMouseClicked
        // TODO add your handling code here:
        String tipoUsuario = UsuarioController.tipoUsuario;
        if(tipoUsuario.equals("aluno")){
            JOptionPane.showMessageDialog(rootPane, "Alunos não podem realizar esta ação!");
        } else if(tipoUsuario.equals("professor")){
            JOptionPane.showMessageDialog(rootPane, "Professores não podem realizar esta ação!");
        } else{
            TelaLivros frame2 = new TelaLivros();

        //populate your frames with stuff
        frame2.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnLivrosMouseClicked

    private void btnAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlunosMouseClicked
        // TODO add your handling code here:
        String tipoUsuario = UsuarioController.tipoUsuario;
        if(tipoUsuario.equals("aluno")){
            JOptionPane.showMessageDialog(rootPane, "Alunos não podem realizar esta ação!");
        } else if(tipoUsuario.equals("professor")){
            JOptionPane.showMessageDialog(rootPane, "Professores não podem realizar esta ação!");
        } else{
        TelaAlunos frame2 = new TelaAlunos();

        //populate your frames with stuff
        frame2.setVisible(true);
        this.dispose();}
    }//GEN-LAST:event_btnAlunosMouseClicked

    private void btnLivrosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLivrosMouseEntered
        // TODO add your handling code here:
        
        TelaUtils.setBotaoClaro(btnLivros);
    }//GEN-LAST:event_btnLivrosMouseEntered

    private void btnLivrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLivrosMouseExited
        // TODO add your handling code here:
        TelaUtils.setBotaoEscuro(btnLivros);
    }//GEN-LAST:event_btnLivrosMouseExited

    private void btnAlunosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlunosMouseEntered
        // TODO add your handling code here:
        TelaUtils.setBotaoClaro(btnAlunos);
    }//GEN-LAST:event_btnAlunosMouseEntered

    private void btnAlunosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlunosMouseExited
        // TODO add your handling code here:
        TelaUtils.setBotaoEscuro(btnAlunos);
    }//GEN-LAST:event_btnAlunosMouseExited

    private void btnProfessoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfessoresMouseEntered
        // TODO add your handling code here:
        TelaUtils.setBotaoClaro(btnProfessores);
    }//GEN-LAST:event_btnProfessoresMouseEntered

    private void btnProfessoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfessoresMouseExited
        // TODO add your handling code here:
        TelaUtils.setBotaoEscuro(btnProfessores);
    }//GEN-LAST:event_btnProfessoresMouseExited

    private void btnFuncionariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseEntered
        // TODO add your handling code here:
        TelaUtils.setBotaoClaro(btnFuncionarios);
    }//GEN-LAST:event_btnFuncionariosMouseEntered

    private void btnFuncionariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseExited
        // TODO add your handling code here:
        TelaUtils.setBotaoEscuro(btnFuncionarios);
    }//GEN-LAST:event_btnFuncionariosMouseExited

    private void btnAluguelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAluguelMouseEntered
        // TODO add your handling code here:
        TelaUtils.setBotaoClaro(btnAluguel);
    }//GEN-LAST:event_btnAluguelMouseEntered

    private void btnAluguelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAluguelMouseExited
        // TODO add your handling code here:
        TelaUtils.setBotaoEscuro(btnAluguel);
    }//GEN-LAST:event_btnAluguelMouseExited

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
        TelaUtils.setBotaoClaro(btnReserva);
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
        TelaUtils.setBotaoEscuro(btnReserva);
    }//GEN-LAST:event_jPanel7MouseExited

    private void btnReservaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservaMouseEntered
        // TODO add your handling code here:
        TelaUtils.setBotaoClaro(btnReserva);
    }//GEN-LAST:event_btnReservaMouseEntered

    private void btnReservaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservaMouseExited
        // TODO add your handling code here:
        TelaUtils.setBotaoEscuro(btnReserva);
    }//GEN-LAST:event_btnReservaMouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10MouseExited

    private void btnProfessoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfessoresMouseClicked
        // TODO add your handling code here:
        String tipoUsuario = UsuarioController.tipoUsuario;
        if(tipoUsuario.equals("aluno")){
            JOptionPane.showMessageDialog(rootPane, "Alunos não podem realizar esta ação!");
        } else if(tipoUsuario.equals("professor")){
            JOptionPane.showMessageDialog(rootPane, "Professores não podem realizar esta ação!");
        } else{
        TelaProfessores frame2 = new TelaProfessores();

        //populate your frames with stuff
        frame2.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_btnProfessoresMouseClicked

    private void btnFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFuncionariosMouseClicked
        // TODO add your handling code here:
        String tipoUsuario = UsuarioController.tipoUsuario;
        if(tipoUsuario.equals("aluno")){
            JOptionPane.showMessageDialog(rootPane, "Alunos não podem realizar esta ação!");
        } else if(tipoUsuario.equals("professor")){
            JOptionPane.showMessageDialog(rootPane, "Professores não podem realizar esta ação!");
        } else{
        TelaFuncionarios frame2 = new TelaFuncionarios();

        //populate your frames with stuff
        frame2.setVisible(true);
        this.dispose();}
    }//GEN-LAST:event_btnFuncionariosMouseClicked

    private void btnAluguelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAluguelMouseClicked
        // TODO add your handling code here:
        TelaAlugueis frame2 = new TelaAlugueis();

        //populate your frames with stuff
        frame2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAluguelMouseClicked

    private void btnReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservaMouseClicked
        // TODO add your handling code here:
        TelaReservas frame2 = new TelaReservas();

        //populate your frames with stuff
        frame2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnReservaMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        LivroController livros = new LivroController();
        txtLivros.setText(livros.listarNumeroDeLivros());
        
        AluguelController alugueis = new AluguelController();
        txtAlugueis.setText(alugueis.listarNumeroDeAlugueis());
        
        ReservaController reservas = new ReservaController();
        txtReservas.setText(reservas.listarNumeroDeReservas());
        
    }//GEN-LAST:event_formWindowActivated

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAluguel;
    private javax.swing.JPanel btnAlunos;
    private javax.swing.JPanel btnFuncionarios;
    private javax.swing.JPanel btnLivros;
    private javax.swing.JPanel btnProfessores;
    private javax.swing.JPanel btnReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel txtAlugueis;
    private javax.swing.JLabel txtLivros;
    private javax.swing.JLabel txtReservas;
    // End of variables declaration//GEN-END:variables
}
